### ISSUE TITLE
Wondering what happened with this repo?

### ISSUE THREAD

**Issue by ma7555** [gmonce/bioscope#1]
I am looking to parse the the bioscope corpus for further training on BERT model. the format is very new to me so I was wondering if you managed to do anything?

**Comment by gmonce** [comment]
Hi, I´ve parsed the bioscope corpus for my thesis. I never had the time to polish the code, but if you want I can upload it here.  The doc is quite ordered... but in Spanish. Just let me know if you are interested.

**Comment by gmonce** [comment]
Take a look at the file proceso.txt to start to understand each step.

**Comment by ma7555** [comment]
Okay will take a look, thanks for getting back to me
